### ISSUE TITLE
Remove code for MODS importer

### ISSUE THREAD

**Issue by val99erie** [UCLALibrary/californica#136]
From discussion with the team, it seems that there was an early attempt to write a MODS importer, but then later it was decided to use CSV instead.  Now we have some dead code lying around for the old MODS importer that we should clean up.

**Tasks**

- [ ] Delete the files under `app/ingest`
- [ ] Delete any specs that correspond to those source files
- [ ] Delete `spec/fixtures/mods_example.xml`
